//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNangcao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int Id { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> ChiTietHDId { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
    
        public virtual ChiTietHD ChiTietHD { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
